// Generated by tools/render-hooks-json.sh --write from tools/hook-gates.txt.
// Gate routes for the opencode host. Do not edit by hand.

export type OpenCodeHook =
  | "tool.execute.before"
  | "experimental.chat.system.transform"
  | "dispose"
  | "event";

export interface OpenCodeGateRoute {
  readonly hook: OpenCodeHook;
  readonly gate: string;
  readonly script: string;
  readonly matcher: string;
  readonly allow: readonly string[];
}

export const routes: readonly OpenCodeGateRoute[] = [
  {
    hook: "tool.execute.before",
    gate: "commit",
    script: "block-commit-until-green.sh",
    matcher: "bash",
    allow: [],
  },
  {
    hook: "tool.execute.before",
    gate: "edits",
    script: "block-edits-without-slice.sh",
    matcher: "edit|write|fallow_fix_apply|apply_patch",
    allow: [],
  },
  {
    hook: "tool.execute.before",
    gate: "unknown",
    script: "block-unknown-tool.sh",
    matcher: ".*",
    allow: ["bash", "apply_patch", "task", "list_mcp_resources", "list_mcp_resource_templates", "read_mcp_resource", "engram_mem_search", "engram_mem_get_observation", "engram_mem_save", "engram_mem_update", "engram_mem_context", "engram_mem_session_summary", "engram_mem_current_project", "engram_mem_save_prompt", "engram_mem_judge", "context7_resolve-library-id", "context7_query-docs", "fallow_find_dupes", "fallow_get_cleanup_candidates", "fallow_audit", "fallow_fix_apply", "edit", "write", "read", "grep", "glob", "skill", "todowrite", "webfetch", "websearch", "question", "lsp", "plan_exit", "oso_plan_approve", "oso_plan_cancel", "oso_wave"],
  },
  {
    hook: "experimental.chat.system.transform",
    gate: "stale",
    script: "warn-stale-state.sh",
    matcher: "",
    allow: [],
  },
  {
    hook: "dispose",
    gate: "teardown",
    script: "cleanup-state.sh",
    matcher: "",
    allow: [],
  },
  {
    hook: "tool.execute.before",
    gate: "proddeploy",
    script: "block-prod-deploy.sh",
    matcher: "bash|.*deploy.*",
    allow: [],
  },
  {
    hook: "event",
    gate: "reanchor",
    script: "reanchor-after-compact.sh",
    matcher: "",
    allow: [],
  }
];
